# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Permanent WIP
email: w2ak@noreply.github.com

#write html inside the double quotes to display in jumbotron
description: "<h1>DevJournal</h1>"

baseurl: "/devjournal" # the subpath of your site, e.g. /blog
url: "https://w2ak.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: w2ak

# Build settings
markdown: kramdown
